/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DiwaliApp;

import databaselibrary.DatabaseLibrary;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bhargav
 */
public class Attendence extends javax.swing.JFrame {

    /**
     * Creates new form Attendence
     */
    DatabaseLibrary dbL;
    Date dNow;
    public Attendence() throws SQLException {
        initComponents();
        getRootPane().setDefaultButton(attendenceSerachButton);
        attendenceFoundLabel.setVisible(false);
        dbL = new DatabaseLibrary("jdbc:mysql://localhost:3316/diwali","root","lkbhargav123KING#@!$%");
    }

    
    private String name;
    private String query;
    private ResultSet rs;
    private String IDType;
    private String time;
    
    SimpleDateFormat ft = 
      new SimpleDateFormat ("hh:mm:ss");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        attendenceName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        attendenceSerachButton = new javax.swing.JButton();
        attendenceFoundLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        attendenceIDCard = new javax.swing.JComboBox();
        attendenceAttendButton = new javax.swing.JButton();
        attendenceClear = new javax.swing.JButton();
        indexNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Attendence");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Attendence");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Enter a registered name:");

        attendenceSerachButton.setText("Search");
        attendenceSerachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceSerachButtonActionPerformed(evt);
            }
        });

        attendenceFoundLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attendenceFoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendenceFoundLabel.setText("Found the Person");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID Card Type:");

        attendenceIDCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student ID", "Driving License", "Passport", "State ID", "SSN", "Custom" }));
        attendenceIDCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceIDCardActionPerformed(evt);
            }
        });

        attendenceAttendButton.setText("Attended");
        attendenceAttendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceAttendButtonActionPerformed(evt);
            }
        });

        attendenceClear.setText("Clear");
        attendenceClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceClearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("or");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Enter the Index Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(113, 113, 113)
                .addComponent(attendenceSerachButton)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(attendenceName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(indexNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(attendenceFoundLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 134, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attendenceIDCard, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attendenceClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(attendenceAttendButton)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendenceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(attendenceSerachButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(attendenceFoundLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendenceIDCard, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendenceAttendButton)
                    .addComponent(attendenceClear))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {attendenceName, indexNumber});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendenceSerachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceSerachButtonActionPerformed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(attendenceAttendButton);
        if(!attendenceName.getText().equals(""))
        {
        name = attendenceName.getText();
        if(attendenceName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Invalid Name, try again with new name");
        }
        else
        {
        query = "select * from registered where name = '"+name+"';";
        try {
            rs = dbL.selectQuery(query);
            rs.next();
            if(rs.getString(2).equals(name))
            {
                attendenceFoundLabel.setVisible(true);
                attendenceFoundLabel.setText("Index: "+rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
        
        
        
        else
        {
            name = indexNumber.getText();
            if(indexNumber.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Invalid Index Number, try again with new name");
            }
            else
            {
            query = "select * from registered where serialNo = '"+name+"';";
            try {
                rs = dbL.selectQuery(query);
                rs.next();
                if(rs.getString(1).equals(name))
                {
                    attendenceFoundLabel.setVisible(true);
                    attendenceFoundLabel.setText("Name: "+rs.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_attendenceSerachButtonActionPerformed

    private void attendenceAttendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceAttendButtonActionPerformed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(attendenceClear);
        if(!attendenceName.getText().equals(""))
        {
        name = attendenceName.getText();
        IDType = (String) attendenceIDCard.getSelectedItem();
        dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat ("hh:mm:ss");
        time = ft.format(dNow);
        query = "update registered set timeAttended = '"+time+"',IDCard = '"+IDType+"' where name ='"+name+"';";
        
        try {
            dbL.updateQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
        {
            try {
                name = indexNumber.getText();
                IDType = (String) attendenceIDCard.getSelectedItem();
                dNow = new Date();
                SimpleDateFormat ft = new SimpleDateFormat ("hh:mm:ss");
                time = ft.format(dNow);
                query = "update registered set timeAttended = '"+time+"',IDCard = '"+IDType+"' where serialNo ="+name+";";
                dbL.updateQuery(query);
                
//        query = "select * from registered where name = '"+name+"';";
//            try {
//                rs = dbL.selectQuery(query);
//                while(rs.next())
//                {
//                    query = "Attended: "+rs.getString(1)+"  "+rs.getString(2)+"  "+rs.getString(3)+"  "+rs.getString(4)+"  "+rs.getString(5)+"  "+rs.getString(6);
//                }
//                new GmailLibrary("mailtosecureyou","mailstodeliver","mailtosecureyou@gmail.com","Secure Backup",query);
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(rootPane, "Error connecting to database");
//            }
            } catch (SQLException ex) {
                Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_attendenceAttendButtonActionPerformed

    private void attendenceClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceClearActionPerformed
        // TODO add your handling code here:
        attendenceName.setText("");
        indexNumber.setText("");
        attendenceIDCard.setSelectedIndex(0);
        attendenceFoundLabel.setVisible(false);
        getRootPane().setDefaultButton(attendenceSerachButton);
    }//GEN-LAST:event_attendenceClearActionPerformed

    private void attendenceIDCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceIDCardActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_attendenceIDCardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendenceAttendButton;
    private javax.swing.JButton attendenceClear;
    private javax.swing.JLabel attendenceFoundLabel;
    private javax.swing.JComboBox attendenceIDCard;
    private javax.swing.JTextField attendenceName;
    private javax.swing.JButton attendenceSerachButton;
    private javax.swing.JTextField indexNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
